//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrioritizerService
{
    using System.Runtime.Serialization;
    using System;
    


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IPrioritizerService")]
    public interface IPrioritizerService
    {
        //[System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getLatestClient", ReplyAction = "http://tempuri.org/IPrioritizerService/getLatestClientResponse")]
        //System.IO.Stream getLatestClient();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getServerVersion", ReplyAction = "http://tempuri.org/IPrioritizerService/getServerVersionResponse")]
        string getServerVersion();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getClientVersion", ReplyAction = "http://tempuri.org/IPrioritizerService/getClientVersionResponse")]
        string getClientVersion();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPrioritizerServiceChannel : IPrioritizerService, System.ServiceModel.IClientChannel
    {
    }


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PrioritizerServiceClient : System.ServiceModel.ClientBase<IPrioritizerService>, IPrioritizerService
    {
        //public ClientPackage getLatestClient()
        //{
        //    return base.Channel.getLatestClient();
        //}

        public string getServerVersion()
        {
            return base.Channel.getServerVersion();
        }

        public string getClientVersion()
        {
            return base.Channel.getClientVersion();
        }
    }


}