using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using PrioritizerService.Model;
using DevExpress.XtraEditors.Repository;
using DevExpress.XtraEditors.Controls;
using System.Linq;
using DevExpress.XtraGrid.Columns;
using Prioritizer.Shared.Model;
using Prioritizer.Proxy;
namespace Prioritizer.Forms
{
    public partial class MeetingCategoriesForm : DevExpress.XtraEditors.XtraForm
    {
        private frmMain _parentForm;
        List<MeetingCategory> deletedRowsList = new List<MeetingCategory>();
        List<MeetingCategory> _MeetingCategoryCollection;
        public MeetingCategoriesForm(frmMain parentForm)
        {
            _parentForm = parentForm;
            _MeetingCategoryCollection = new List<MeetingCategory>(ConnectionManager.Proxy.getMeetingCategoryList(true, frmMain.loggedInUserID, frmMain._tenantID)); ;
            InitializeComponent();

        }



        private void SetGridProperties()
        {
            //gridView1.OptionsBehavior.Editable= false;
        }

        private void SetColumnsProperties()
        {

            hideUnnecessaryColumns();
            removeAutoGeneratedColumns();
            bindComboToGrid();
        }

        private void bindComboToGrid()
        {
            
        }

     

        private void removeAutoGeneratedColumns()
        {
            gridView1.Columns.Remove(gridView1.Columns["changetracker"]);
        }

        private void hideUnnecessaryColumns()
        {
            for (int x = 0; x < gridView1.Columns.Count; x++)
                gridView1.Columns[x].Visible = false;

            gridView1.Columns["CategoryName"].Visible = true;
            
        }




        void gridView1_RowUpdated(object sender, DevExpress.XtraGrid.Views.Base.RowObjectEventArgs e)
        {
        }

        protected override bool ProcessCmdKey(ref Message msg, Keys keyData)
        {
            if (keyData == Keys.Escape) this.Close();
            return base.ProcessCmdKey(ref msg, keyData);
        }

        private void usersGrid_Load(object sender, EventArgs e)
        {

        }

        private void MeetingCategoryForm_Load(object sender, EventArgs e)
        {
            MeetingCategoryGrid.DataSource = _MeetingCategoryCollection;
            

            SetGridProperties();
            SetColumnsProperties();
        }

        private void usersGrid_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyData == Keys.Delete)
            {
                var selectedRowHandle = gridView1.GetSelectedRows()[0];
                deletedRowsList.Add(gridView1.GetRow(selectedRowHandle) as MeetingCategory);
                gridView1.DeleteRow(selectedRowHandle);
            }
        }

        private void MeetingCategoryGrid_Click(object sender, EventArgs e)
        {
            
        }


        private void btnSave_Click(object sender, EventArgs e)
        {
            //deleted rows
            if (deletedRowsList.Count > 0)
            {
                foreach (var x in deletedRowsList)
                {
                    if (x != null)
                        ConnectionManager.Proxy.deleteMeetingCategory(x);
                }
                deletedRowsList.Clear();
            }

            //modified or added rows
            foreach (MeetingCategory mc in _MeetingCategoryCollection)
            {
                if (mc.ChangeTracker.State != ObjectState.Unchanged)
                {
                    mc.TenantID = frmMain._tenantID;
                    ConnectionManager.Proxy.applyChangesMeetingCategory(mc, frmMain._tenantID);
                }
            }
            this.Close();
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.Close();
        }   
    }
}