//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace PrioritizerService.Model
{
    [DataContract(IsReference = true)]
    [Serializable]
    [KnownType(typeof(Users))]
    [KnownType(typeof(Meetings))]
    [KnownType(typeof(Tenant))]
    public partial class MeetingAttendies: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid ID
        {
            get { return _iD; }
            set
            {
                if (_iD != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iD = value;
                    OnPropertyChanged("ID");
                }
            }
        }
        private System.Guid _iD;
    
        [DataMember]
        public System.Guid MeetingID
        {
            get { return _meetingID; }
            set
            {
                if (_meetingID != value)
                {
                    ChangeTracker.RecordOriginalValue("MeetingID", _meetingID);
      if (!IsDeserializing)
      {
                          if (Meetings != null && Meetings.ID != value)
                        {
                            Meetings = null;
                        }
                    }
                    _meetingID = value;
                    OnPropertyChanged("MeetingID");
                }
            }
        }
        private System.Guid _meetingID;
    
        [DataMember]
        public System.Guid AttendeeID
        {
            get { return _attendeeID; }
            set
            {
                if (_attendeeID != value)
                {
                    ChangeTracker.RecordOriginalValue("AttendeeID", _attendeeID);
      if (!IsDeserializing)
      {
                          if (Users != null && Users.ID != value)
                        {
                            Users = null;
                        }
                    }
                    _attendeeID = value;
                    OnPropertyChanged("AttendeeID");
                }
            }
        }
        private System.Guid _attendeeID;
    
        [DataMember]
        public System.Guid TenantID
        {
            get { return _tenantID; }
            set
            {
                if (_tenantID != value)
                {
                    ChangeTracker.RecordOriginalValue("TenantID", _tenantID);
      if (!IsDeserializing)
      {
                          if (Tenant != null && Tenant.ID != value)
                        {
                            Tenant = null;
                        }
                    }
                    _tenantID = value;
                    OnPropertyChanged("TenantID");
                }
            }
        }
        private System.Guid _tenantID;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Users Users
        {
            get { return _users; }
            set
            {
                if (!ReferenceEquals(_users, value))
                {
                    var previousValue = _users;
                    _users = value;
                    FixupUsers(previousValue);
                    OnNavigationPropertyChanged("Users");
                }
            }
        }
        private Users _users;
    
        [DataMember]
        public Meetings Meetings
        {
            get { return _meetings; }
            set
            {
                if (!ReferenceEquals(_meetings, value))
                {
                    var previousValue = _meetings;
                    _meetings = value;
                    FixupMeetings(previousValue);
                    OnNavigationPropertyChanged("Meetings");
                }
            }
        }
        private Meetings _meetings;
    
        [DataMember]
        public Tenant Tenant
        {
            get { return _tenant; }
            set
            {
                if (!ReferenceEquals(_tenant, value))
                {
                    var previousValue = _tenant;
                    _tenant = value;
                    FixupTenant(previousValue);
                    OnNavigationPropertyChanged("Tenant");
                }
            }
        }
        private Tenant _tenant;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Users = null;
            Meetings = null;
            Tenant = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupUsers(Users previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.MeetingAttendies.Contains(this))
            {
                previousValue.MeetingAttendies.Remove(this);
            }
    
            if (Users != null)
            {
                if (!Users.MeetingAttendies.Contains(this))
                {
                    Users.MeetingAttendies.Add(this);
                }
    
                AttendeeID = Users.ID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Users")
                    && (ChangeTracker.OriginalValues["Users"] == Users))
                {
                    ChangeTracker.OriginalValues.Remove("Users");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Users", previousValue);
                }
                if (Users != null && !Users.ChangeTracker.ChangeTrackingEnabled)
                {
                    Users.StartTracking();
                }
            }
        }
    
        private void FixupMeetings(Meetings previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.MeetingAttendies.Contains(this))
            {
                previousValue.MeetingAttendies.Remove(this);
            }
    
            if (Meetings != null)
            {
                if (!Meetings.MeetingAttendies.Contains(this))
                {
                    Meetings.MeetingAttendies.Add(this);
                }
    
                MeetingID = Meetings.ID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Meetings")
                    && (ChangeTracker.OriginalValues["Meetings"] == Meetings))
                {
                    ChangeTracker.OriginalValues.Remove("Meetings");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Meetings", previousValue);
                }
                if (Meetings != null && !Meetings.ChangeTracker.ChangeTrackingEnabled)
                {
                    Meetings.StartTracking();
                }
            }
        }
    
        private void FixupTenant(Tenant previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.MeetingAttendies.Contains(this))
            {
                previousValue.MeetingAttendies.Remove(this);
            }
    
            if (Tenant != null)
            {
                if (!Tenant.MeetingAttendies.Contains(this))
                {
                    Tenant.MeetingAttendies.Add(this);
                }
    
                TenantID = Tenant.ID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Tenant")
                    && (ChangeTracker.OriginalValues["Tenant"] == Tenant))
                {
                    ChangeTracker.OriginalValues.Remove("Tenant");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Tenant", previousValue);
                }
                if (Tenant != null && !Tenant.ChangeTracker.ChangeTrackingEnabled)
                {
                    Tenant.StartTracking();
                }
            }
        }

        #endregion
    }
}
