using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Prioritizer.Proxy
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:2.0.50727.6407
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------



    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IDurableService")]
    public interface IDurableService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDurableService/DoWork", ReplyAction = "http://tempuri.org/IDurableService/DoWorkResponse")]
        void DoWork();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDurableService/EndPersistence", ReplyAction = "http://tempuri.org/IDurableService/EndPersistenceResponse")]
        void EndPersistence();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IDurableServiceChannel : IDurableService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DurableServiceClient : System.ServiceModel.ClientBase<IDurableService>, IDurableService
    {

        public DurableServiceClient()
        {
        }

        public DurableServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public DurableServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public DurableServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public DurableServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public void DoWork()
        {
            base.Channel.DoWork();
        }

        public void EndPersistence()
        {
            base.Channel.EndPersistence();
        }
    }

}
