//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5456
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrioritizerService.Model
{
    using System.Runtime.Serialization;
    using System;
    //using Shared;
    using Prioritizer.Shared;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IPrioritizerService")]
    public interface IPrioritizerService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/sendInvitationMail", ReplyAction = "http://tempuri.org/IPrioritizerService/sendInvitationMailResponse")]
        void sendInvitationMail(Prioritizer.Shared.Model.Users u, System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/DomainControllerAuthenticate", ReplyAction = "http://tempuri.org/IPrioritizerService/DomainControllerAuthenticateResponse")]
        bool DomainControllerAuthenticate();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/Authenticate", ReplyAction = "http://tempuri.org/IPrioritizerService/AuthenticateResponse")]
        Prioritizer.Shared.Model.Users Authenticate(string username, string password, string company);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getLatestClient", ReplyAction = "http://tempuri.org/IPrioritizerService/getLatestClientResponse")]
        Prioritizer.Shared.ClientPackage getLatestClient();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/ping", ReplyAction = "http://tempuri.org/IPrioritizerService/pingResponse")]
        Prioritizer.Shared.ClientMessage ping(System.Guid userID, System.DateTime lastUpdate);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/ClientMessageReceiveConfirmation", ReplyAction = "http://tempuri.org/IPrioritizerService/ClientMessageReceiveConfirmationResponse")]
        void ClientMessageReceiveConfirmation(System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/Poke", ReplyAction = "http://tempuri.org/IPrioritizerService/PokeResponse")]
        void Poke(Prioritizer.Shared.Poke p);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/HelloWorld", ReplyAction = "http://tempuri.org/IPrioritizerService/HelloWorldResponse")]
        string HelloWorld(int input);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getAlertsForUser", ReplyAction = "http://tempuri.org/IPrioritizerService/getAlertsForUserResponse")]
        Prioritizer.Shared.Model.Alerts[] getAlertsForUser(System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getAlertForTask", ReplyAction = "http://tempuri.org/IPrioritizerService/getAlertForTaskResponse")]
        Prioritizer.Shared.Model.Alerts[] getAlertForTask(System.Guid taskID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesAlerts", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesAlertsResponse")]
        void applyChangesAlerts(Prioritizer.Shared.Model.Alerts a, System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteAlert", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteAlertResponse")]
        void deleteAlert(Prioritizer.Shared.Model.Alerts a);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getUsersList", ReplyAction = "http://tempuri.org/IPrioritizerService/getUsersListResponse")]
        Prioritizer.Shared.Model.Users[] getUsersList(System.Nullable<System.Guid> tenantID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteMeetingCategory", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteMeetingCategoryResponse")]
        void deleteMeetingCategory(Prioritizer.Shared.Model.MeetingCategory mc);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesMeetingCategory", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesMeetingCategoryResponse")]
        void applyChangesMeetingCategory(Prioritizer.Shared.Model.MeetingCategory mc, System.Nullable<System.Guid> tenantID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteMeetings", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteMeetingsResponse")]
        void deleteMeetings(Prioritizer.Shared.Model.Meetings m);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesMeetings", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesMeetingsResponse")]
        void applyChangesMeetings(Prioritizer.Shared.Model.Meetings m, System.Nullable<System.Guid> tenantID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteTasks", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteTasksResponse")]
        void deleteTasks(Prioritizer.Shared.Model.Tasks t);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/addTask", ReplyAction = "http://tempuri.org/IPrioritizerService/addTaskResponse")]
        Prioritizer.Shared.Model.Tasks addTask(Prioritizer.Shared.Model.Tasks t, System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesMeetingTasksList", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesMeetingTasksListResponse")]
        void applyChangesMeetingTasksList(Prioritizer.Shared.Model.MeetingTasks[] changedMeetingTasksList);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesTasksList", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesTasksListResponse")]
        Prioritizer.Shared.TaskSaveFailure[] applyChangesTasksList(Prioritizer.Shared.Model.Tasks[] changedTasksList, System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesTasks", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesTasksResponse")]
        Prioritizer.Shared.Model.Tasks applyChangesTasks(Prioritizer.Shared.Model.Tasks t, System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteMeetingTasks", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteMeetingTasksResponse")]
        void deleteMeetingTasks(Prioritizer.Shared.Model.MeetingTasks mt);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesMeetingTasks", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesMeetingTasksResponse")]
        void applyChangesMeetingTasks(Prioritizer.Shared.Model.MeetingTasks mt);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteMeetingCategoryMap", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteMeetingCategoryMapResponse")]
        void deleteMeetingCategoryMap(Prioritizer.Shared.Model.MeetingCategoryMap mcm);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesMeetingCategoryMap", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesMeetingCategoryMapResponse")]
        void applyChangesMeetingCategoryMap(Prioritizer.Shared.Model.MeetingCategoryMap mcm);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteProjects", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteProjectsResponse")]
        void deleteProjects(Prioritizer.Shared.Model.projects p);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesProjects", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesProjectsResponse")]
        void applyChangesProjects(Prioritizer.Shared.Model.projects p, System.Nullable<System.Guid> tenantID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteUsers", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteUsersResponse")]
        void deleteUsers(Prioritizer.Shared.Model.Users u);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesUsers", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesUsersResponse")]
        Prioritizer.Shared.Model.Users applyChangesUsers(Prioritizer.Shared.Model.Users u, System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteManagerTeamMemberRelations", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteManagerTeamMemberRelationsResponse")]
        void deleteManagerTeamMemberRelations(Prioritizer.Shared.Model.ManagerTeamMemberRelations mtr);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesManagerTeamMemberRelations", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesManagerTeamMemberRelationsResp" +
            "onse")]
        void applyChangesManagerTeamMemberRelations(Prioritizer.Shared.Model.ManagerTeamMemberRelations mtr);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteMeetingAttendies", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteMeetingAttendiesResponse")]
        void deleteMeetingAttendies(Prioritizer.Shared.Model.MeetingAttendies ma);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesMeetingAttendies", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesMeetingAttendiesResponse")]
        void applyChangesMeetingAttendies(Prioritizer.Shared.Model.MeetingAttendies ma);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getUsers", ReplyAction = "http://tempuri.org/IPrioritizerService/getUsersResponse")]
        Prioritizer.Shared.Model.Users[] getUsers(System.Nullable<System.Guid> tenantID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/moveAllTasksPriorityForUser", ReplyAction = "http://tempuri.org/IPrioritizerService/moveAllTasksPriorityForUserResponse")]
        void moveAllTasksPriorityForUser(int numOfSteps, System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getTaskByID", ReplyAction = "http://tempuri.org/IPrioritizerService/getTaskByIDResponse")]
        Prioritizer.Shared.Model.Tasks getTaskByID(System.Guid taskID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getTasksByIDs", ReplyAction = "http://tempuri.org/IPrioritizerService/getTasksByIDsResponse")]
        Prioritizer.Shared.Model.Tasks[] getTasksByIDs(System.Guid[] taskIDs);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getUserByID", ReplyAction = "http://tempuri.org/IPrioritizerService/getUserByIDResponse")]
        Prioritizer.Shared.Model.Users getUserByID(System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getUserByDomainName", ReplyAction = "http://tempuri.org/IPrioritizerService/getUserByDomainNameResponse")]
        Prioritizer.Shared.Model.Users[] getUserByDomainName(string domainName, System.Nullable<System.Guid> tenantID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getMeetingTaskByID", ReplyAction = "http://tempuri.org/IPrioritizerService/getMeetingTaskByIDResponse")]
        Prioritizer.Shared.Model.MeetingTasks getMeetingTaskByID(System.Guid taskID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getMeetingTasksByID", ReplyAction = "http://tempuri.org/IPrioritizerService/getMeetingTasksByIDResponse")]
        Prioritizer.Shared.Model.MeetingTasks[] getMeetingTasksByID(System.Guid taskID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getMeetingCategoryMapByID", ReplyAction = "http://tempuri.org/IPrioritizerService/getMeetingCategoryMapByIDResponse")]
        Prioritizer.Shared.Model.MeetingCategoryMap getMeetingCategoryMapByID(System.Guid meetingID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getMeetingByID", ReplyAction = "http://tempuri.org/IPrioritizerService/getMeetingByIDResponse")]
        Prioritizer.Shared.Model.Meetings getMeetingByID(System.Guid meetingID, bool includeTasks);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getTasksForMeeting", ReplyAction = "http://tempuri.org/IPrioritizerService/getTasksForMeetingResponse")]
        Prioritizer.Shared.Model.Tasks[] getTasksForMeeting(System.Guid meetingID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getMeetingByName", ReplyAction = "http://tempuri.org/IPrioritizerService/getMeetingByNameResponse")]
        Prioritizer.Shared.Model.Meetings getMeetingByName(string meetingName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/findAllTeamMembersAllowedForUser", ReplyAction = "http://tempuri.org/IPrioritizerService/findAllTeamMembersAllowedForUserResponse")]
        Prioritizer.Shared.Model.ManagerTeamMemberRelations[] findAllTeamMembersAllowedForUser(System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getMeetingCategoryList", ReplyAction = "http://tempuri.org/IPrioritizerService/getMeetingCategoryListResponse")]
        Prioritizer.Shared.Model.MeetingCategory[] getMeetingCategoryList(bool filterCategoriesOnlyForLoggedInUser, System.Guid userID, System.Guid tenantID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getMeetingList", ReplyAction = "http://tempuri.org/IPrioritizerService/getMeetingListResponse")]
        Prioritizer.Shared.Model.Meetings[] getMeetingList(System.Guid meetingCategory, System.Guid userID, bool includeFinished, System.Nullable<System.Guid> tenantID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getTasksForUser", ReplyAction = "http://tempuri.org/IPrioritizerService/getTasksForUserResponse")]
        Prioritizer.Shared.Model.Tasks[] getTasksForUser(bool includeFinishedTasks, bool includeCancelledTasks, System.Guid userID, System.Guid requestingUserID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getTasksForTeamMembers", ReplyAction = "http://tempuri.org/IPrioritizerService/getTasksForTeamMembersResponse")]
        Prioritizer.Shared.Model.Tasks[] getTasksForTeamMembers(bool includeFinishedTasks, bool includeCancelledTasks, System.Guid userID, System.Guid requestingUserID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getTaskStatusList", ReplyAction = "http://tempuri.org/IPrioritizerService/getTaskStatusListResponse")]
        Prioritizer.Shared.Model.TaskStatus[] getTaskStatusList();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getProjectList", ReplyAction = "http://tempuri.org/IPrioritizerService/getProjectListResponse")]
        Prioritizer.Shared.Model.projects[] getProjectList(System.Nullable<System.Guid> tenantID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getManagerTeamMemberRelationsList", ReplyAction = "http://tempuri.org/IPrioritizerService/getManagerTeamMemberRelationsListResponse")]
        Prioritizer.Shared.Model.ManagerTeamMemberRelations[] getManagerTeamMemberRelationsList(System.Nullable<System.Guid> tenantID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getMeetingsForOwner", ReplyAction = "http://tempuri.org/IPrioritizerService/getMeetingsForOwnerResponse")]
        Prioritizer.Shared.Model.Meetings[] getMeetingsForOwner(System.Guid ownerUserID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/relationExists", ReplyAction = "http://tempuri.org/IPrioritizerService/relationExistsResponse")]
        bool relationExists(System.Guid managerID, System.Guid teamMemberID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/forwardTo", ReplyAction = "http://tempuri.org/IPrioritizerService/forwardToResponse")]
        void forwardTo(System.Guid taskID, System.Guid targetUserID, System.Guid loggedInUserID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/copyTo", ReplyAction = "http://tempuri.org/IPrioritizerService/copyToResponse")]
        void copyTo(System.Guid taskID, System.Guid targetUserID, System.Guid loggedInUserID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getMeetingAttendees", ReplyAction = "http://tempuri.org/IPrioritizerService/getMeetingAttendeesResponse")]
        Prioritizer.Shared.Model.MeetingAttendies[] getMeetingAttendees(System.Guid meetingID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getMeetingAttendeesUserList", ReplyAction = "http://tempuri.org/IPrioritizerService/getMeetingAttendeesUserListResponse")]
        Prioritizer.Shared.Model.Users[] getMeetingAttendeesUserList(System.Guid meetingID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/deleteAttachment", ReplyAction = "http://tempuri.org/IPrioritizerService/deleteAttachmentResponse")]
        void deleteAttachment(Prioritizer.Shared.Model.attachments a, System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/applyChangesAttachments", ReplyAction = "http://tempuri.org/IPrioritizerService/applyChangesAttachmentsResponse")]
        void applyChangesAttachments(Prioritizer.Shared.Model.attachments a);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/addAttachment", ReplyAction = "http://tempuri.org/IPrioritizerService/addAttachmentResponse")]
        void addAttachment(Prioritizer.Shared.Model.attachments a, System.Guid userID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getAttachmentsForTask", ReplyAction = "http://tempuri.org/IPrioritizerService/getAttachmentsForTaskResponse")]
        Prioritizer.Shared.Model.attachments[] getAttachmentsForTask(System.Guid taskID);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getShowTaskURL", ReplyAction = "http://tempuri.org/IPrioritizerService/getShowTaskURLResponse")]
        string getShowTaskURL();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getServerVersion", ReplyAction = "http://tempuri.org/IPrioritizerService/getServerVersionResponse")]
        string getServerVersion();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IPrioritizerService/getClientVersion", ReplyAction = "http://tempuri.org/IPrioritizerService/getClientVersionResponse")]
        string getClientVersion();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface IPrioritizerServiceChannel : IPrioritizerService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PrioritizerServiceClient : System.ServiceModel.ClientBase<IPrioritizerService>, IPrioritizerService
    {

        public PrioritizerServiceClient()
        {
        }

        public PrioritizerServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public PrioritizerServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public PrioritizerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public PrioritizerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public void sendInvitationMail(Prioritizer.Shared.Model.Users u, System.Guid userID)
        {
            base.Channel.sendInvitationMail(u, userID);
        }

        public bool DomainControllerAuthenticate()
        {
            return base.Channel.DomainControllerAuthenticate();
        }

        public Prioritizer.Shared.Model.Users Authenticate(string username, string password, string company)
        {
            return base.Channel.Authenticate(username, password, company);
        }

        public Prioritizer.Shared.ClientPackage getLatestClient()
        {
            return base.Channel.getLatestClient();
        }

        public Prioritizer.Shared.ClientMessage ping(System.Guid userID, System.DateTime lastUpdate)
        {
            return base.Channel.ping(userID, lastUpdate);
        }

        public void ClientMessageReceiveConfirmation(System.Guid userID)
        {
            base.Channel.ClientMessageReceiveConfirmation(userID);
        }

        public void Poke(Prioritizer.Shared.Poke p)
        {
            base.Channel.Poke(p);
        }

        public string HelloWorld(int input)
        {
            return base.Channel.HelloWorld(input);
        }

        public Prioritizer.Shared.Model.Alerts[] getAlertsForUser(System.Guid userID)
        {
            return base.Channel.getAlertsForUser(userID);
        }

        public Prioritizer.Shared.Model.Alerts[] getAlertForTask(System.Guid taskID)
        {
            return base.Channel.getAlertForTask(taskID);
        }

        public void applyChangesAlerts(Prioritizer.Shared.Model.Alerts a, System.Guid userID)
        {
            base.Channel.applyChangesAlerts(a, userID);
        }

        public void deleteAlert(Prioritizer.Shared.Model.Alerts a)
        {
            base.Channel.deleteAlert(a);
        }

        public Prioritizer.Shared.Model.Users[] getUsersList(System.Nullable<System.Guid> tenantID)
        {
            return base.Channel.getUsersList(tenantID);
        }

        public void deleteMeetingCategory(Prioritizer.Shared.Model.MeetingCategory mc)
        {
            base.Channel.deleteMeetingCategory(mc);
        }

        public void applyChangesMeetingCategory(Prioritizer.Shared.Model.MeetingCategory mc, System.Nullable<System.Guid> tenantID)
        {
            base.Channel.applyChangesMeetingCategory(mc, tenantID);
        }

        public void deleteMeetings(Prioritizer.Shared.Model.Meetings m)
        {
            base.Channel.deleteMeetings(m);
        }

        public void applyChangesMeetings(Prioritizer.Shared.Model.Meetings m, System.Nullable<System.Guid> tenantID)
        {
            base.Channel.applyChangesMeetings(m, tenantID);
        }

        public void deleteTasks(Prioritizer.Shared.Model.Tasks t)
        {
            base.Channel.deleteTasks(t);
        }

        public Prioritizer.Shared.Model.Tasks addTask(Prioritizer.Shared.Model.Tasks t, System.Guid userID)
        {
            return base.Channel.addTask(t, userID);
        }

        public void applyChangesMeetingTasksList(Prioritizer.Shared.Model.MeetingTasks[] changedMeetingTasksList)
        {
            base.Channel.applyChangesMeetingTasksList(changedMeetingTasksList);
        }

        public Prioritizer.Shared.TaskSaveFailure[] applyChangesTasksList(Prioritizer.Shared.Model.Tasks[] changedTasksList, System.Guid userID)
        {
            return base.Channel.applyChangesTasksList(changedTasksList, userID);
        }

        public Prioritizer.Shared.Model.Tasks applyChangesTasks(Prioritizer.Shared.Model.Tasks t, System.Guid userID)
        {
            return base.Channel.applyChangesTasks(t, userID);
        }

        public void deleteMeetingTasks(Prioritizer.Shared.Model.MeetingTasks mt)
        {
            base.Channel.deleteMeetingTasks(mt);
        }

        public void applyChangesMeetingTasks(Prioritizer.Shared.Model.MeetingTasks mt)
        {
            base.Channel.applyChangesMeetingTasks(mt);
        }

        public void deleteMeetingCategoryMap(Prioritizer.Shared.Model.MeetingCategoryMap mcm)
        {
            base.Channel.deleteMeetingCategoryMap(mcm);
        }

        public void applyChangesMeetingCategoryMap(Prioritizer.Shared.Model.MeetingCategoryMap mcm)
        {
            base.Channel.applyChangesMeetingCategoryMap(mcm);
        }

        public void deleteProjects(Prioritizer.Shared.Model.projects p)
        {
            base.Channel.deleteProjects(p);
        }

        public void applyChangesProjects(Prioritizer.Shared.Model.projects p, System.Nullable<System.Guid> tenantID)
        {
            base.Channel.applyChangesProjects(p, tenantID);
        }

        public void deleteUsers(Prioritizer.Shared.Model.Users u)
        {
            base.Channel.deleteUsers(u);
        }

        public Prioritizer.Shared.Model.Users applyChangesUsers(Prioritizer.Shared.Model.Users u, System.Guid userID)
        {
            return base.Channel.applyChangesUsers(u, userID);
        }

        public void deleteManagerTeamMemberRelations(Prioritizer.Shared.Model.ManagerTeamMemberRelations mtr)
        {
            base.Channel.deleteManagerTeamMemberRelations(mtr);
        }

        public void applyChangesManagerTeamMemberRelations(Prioritizer.Shared.Model.ManagerTeamMemberRelations mtr)
        {
            base.Channel.applyChangesManagerTeamMemberRelations(mtr);
        }

        public void deleteMeetingAttendies(Prioritizer.Shared.Model.MeetingAttendies ma)
        {
            base.Channel.deleteMeetingAttendies(ma);
        }

        public void applyChangesMeetingAttendies(Prioritizer.Shared.Model.MeetingAttendies ma)
        {
            base.Channel.applyChangesMeetingAttendies(ma);
        }

        public Prioritizer.Shared.Model.Users[] getUsers(System.Nullable<System.Guid> tenantID)
        {
            return base.Channel.getUsers(tenantID);
        }

        public void moveAllTasksPriorityForUser(int numOfSteps, System.Guid userID)
        {
            base.Channel.moveAllTasksPriorityForUser(numOfSteps, userID);
        }

        public Prioritizer.Shared.Model.Tasks getTaskByID(System.Guid taskID)
        {
            return base.Channel.getTaskByID(taskID);
        }

        public Prioritizer.Shared.Model.Tasks[] getTasksByIDs(System.Guid[] taskIDs)
        {
            return base.Channel.getTasksByIDs(taskIDs);
        }

        public Prioritizer.Shared.Model.Users getUserByID(System.Guid userID)
        {
            return base.Channel.getUserByID(userID);
        }

        public Prioritizer.Shared.Model.Users[] getUserByDomainName(string domainName, System.Nullable<System.Guid> tenantID)
        {
            return base.Channel.getUserByDomainName(domainName, tenantID);
        }

        public Prioritizer.Shared.Model.MeetingTasks getMeetingTaskByID(System.Guid taskID)
        {
            return base.Channel.getMeetingTaskByID(taskID);
        }

        public Prioritizer.Shared.Model.MeetingTasks[] getMeetingTasksByID(System.Guid taskID)
        {
            return base.Channel.getMeetingTasksByID(taskID);
        }

        public Prioritizer.Shared.Model.MeetingCategoryMap getMeetingCategoryMapByID(System.Guid meetingID)
        {
            return base.Channel.getMeetingCategoryMapByID(meetingID);
        }

        public Prioritizer.Shared.Model.Meetings getMeetingByID(System.Guid meetingID, bool includeTasks)
        {
            return base.Channel.getMeetingByID(meetingID, includeTasks);
        }

        public Prioritizer.Shared.Model.Tasks[] getTasksForMeeting(System.Guid meetingID)
        {
            return base.Channel.getTasksForMeeting(meetingID);
        }

        public Prioritizer.Shared.Model.Meetings getMeetingByName(string meetingName)
        {
            return base.Channel.getMeetingByName(meetingName);
        }

        public Prioritizer.Shared.Model.ManagerTeamMemberRelations[] findAllTeamMembersAllowedForUser(System.Guid userID)
        {
            return base.Channel.findAllTeamMembersAllowedForUser(userID);
        }

        public Prioritizer.Shared.Model.MeetingCategory[] getMeetingCategoryList(bool filterCategoriesOnlyForLoggedInUser, System.Guid userID, System.Guid tenantID)
        {
            return base.Channel.getMeetingCategoryList(filterCategoriesOnlyForLoggedInUser, userID, tenantID);
        }

        public Prioritizer.Shared.Model.Meetings[] getMeetingList(System.Guid meetingCategory, System.Guid userID, bool includeFinished, System.Nullable<System.Guid> tenantID)
        {
            return base.Channel.getMeetingList(meetingCategory, userID, includeFinished, tenantID);
        }

        public Prioritizer.Shared.Model.Tasks[] getTasksForUser(bool includeFinishedTasks, bool includeCancelledTasks, System.Guid userID, System.Guid requestingUserID)
        {
            return base.Channel.getTasksForUser(includeFinishedTasks, includeCancelledTasks, userID, requestingUserID);
        }

        public Prioritizer.Shared.Model.Tasks[] getTasksForTeamMembers(bool includeFinishedTasks, bool includeCancelledTasks, System.Guid userID, System.Guid requestingUserID)
        {
            return base.Channel.getTasksForTeamMembers(includeFinishedTasks, includeCancelledTasks, userID, requestingUserID);
        }

        public Prioritizer.Shared.Model.TaskStatus[] getTaskStatusList()
        {
            return base.Channel.getTaskStatusList();
        }

        public Prioritizer.Shared.Model.projects[] getProjectList(System.Nullable<System.Guid> tenantID)
        {
            return base.Channel.getProjectList(tenantID);
        }

        public Prioritizer.Shared.Model.ManagerTeamMemberRelations[] getManagerTeamMemberRelationsList(System.Nullable<System.Guid> tenantID)
        {
            return base.Channel.getManagerTeamMemberRelationsList(tenantID);
        }

        public Prioritizer.Shared.Model.Meetings[] getMeetingsForOwner(System.Guid ownerUserID)
        {
            return base.Channel.getMeetingsForOwner(ownerUserID);
        }

        public bool relationExists(System.Guid managerID, System.Guid teamMemberID)
        {
            return base.Channel.relationExists(managerID, teamMemberID);
        }

        public void forwardTo(System.Guid taskID, System.Guid targetUserID, System.Guid loggedInUserID)
        {
            base.Channel.forwardTo(taskID, targetUserID, loggedInUserID);
        }

        public void copyTo(System.Guid taskID, System.Guid targetUserID, System.Guid loggedInUserID)
        {
            base.Channel.copyTo(taskID, targetUserID, loggedInUserID);
        }

        public Prioritizer.Shared.Model.MeetingAttendies[] getMeetingAttendees(System.Guid meetingID)
        {
            return base.Channel.getMeetingAttendees(meetingID);
        }

        public Prioritizer.Shared.Model.Users[] getMeetingAttendeesUserList(System.Guid meetingID)
        {
            return base.Channel.getMeetingAttendeesUserList(meetingID);
        }

        public void deleteAttachment(Prioritizer.Shared.Model.attachments a, System.Guid userID)
        {
            base.Channel.deleteAttachment(a, userID);
        }

        public void applyChangesAttachments(Prioritizer.Shared.Model.attachments a)
        {
            base.Channel.applyChangesAttachments(a);
        }

        public void addAttachment(Prioritizer.Shared.Model.attachments a, System.Guid userID)
        {
            base.Channel.addAttachment(a, userID);
        }

        public Prioritizer.Shared.Model.attachments[] getAttachmentsForTask(System.Guid taskID)
        {
            return base.Channel.getAttachmentsForTask(taskID);
        }

        public string getShowTaskURL()
        {
            return base.Channel.getShowTaskURL();
        }

        public string getServerVersion()
        {
            return base.Channel.getServerVersion();
        }

        public string getClientVersion()
        {
            return base.Channel.getClientVersion();
        }
    }

}